import {
  app,
  BrowserWindow,
  ipcMain,
  systemPreferences,
  dialog,
  desktopCapturer,
} from "electron";
import path from "path";
import Store from "electron-store";
import { initMain } from "electron-audio-loopback";

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
try {
  if (require("electron-squirrel-startup")) {
    app.quit();
  }
} catch (error) {
  // electron-squirrel-startup is not available, continue normally
}

// Initialize electron store
const store = new Store();

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Vite
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_VITE_DEV_SERVER_URL: string;
declare const MAIN_WINDOW_VITE_NAME: string;

let mainWindow: BrowserWindow | null = null;

const createWindow = (): void => {
  // Create the browser window.
  mainWindow = new BrowserWindow({
    width: 1200,
    height: 800,
    minWidth: 1000,
    minHeight: 600,
    titleBarStyle: "default",
    backgroundColor: "#ffffff",
    movable: true,
    webPreferences: {
      preload: path.join(__dirname, "preload.js"),
      nodeIntegration: false,
      contextIsolation: true,
    },
  });

  // and load the index.html of the app.
  if (MAIN_WINDOW_VITE_DEV_SERVER_URL) {
    mainWindow.loadURL(MAIN_WINDOW_VITE_DEV_SERVER_URL);
  } else {
    mainWindow.loadFile(
      path.join(__dirname, `../renderer/${MAIN_WINDOW_VITE_NAME}/index.html`),
    );
  }
};

// Request audio permissions on macOS
const requestAudioPermissions = async () => {
  if (process.platform === "darwin") {
    // Request microphone permission
    const microphoneStatus =
      systemPreferences.getMediaAccessStatus("microphone");

    if (microphoneStatus !== "granted") {
      const granted = await systemPreferences.askForMediaAccess("microphone");
      if (!granted) {
        dialog.showMessageBox({
          type: "warning",
          title: "Microphone access required",
          message: "This app requires microphone access to record meetings.",
          buttons: ["OK"],
        });
      }
    }
  }
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on("ready", () => {
  createWindow();
  requestAudioPermissions();

  // Initialize audio loopback plugin
  initMain();
});

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on("window-all-closed", () => {
  if (process.platform !== "darwin") {
    app.quit();
  }
});

app.on("activate", () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

// IPC handlers
ipcMain.handle("get-app-path", () => {
  return app.getPath("userData");
});

ipcMain.handle("store-get", (_, key: string) => {
  return (store as any).get(key, null);
});

ipcMain.handle("store-set", (_, key: string, value: any) => {
  (store as any).set(key, value);
  return true;
});

ipcMain.handle("store-delete", (_, key: string) => {
  (store as any).delete(key);
  return true;
});
