import {
  app,
  BrowserWindow,
  ipcMain,
  systemPreferences,
  dialog,
  desktopCapturer,
} from "electron";
import path from "path";
import Store from "electron-store";

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require("electron-squirrel-startup")) {
  app.quit();
}

// Initialize electron store
const store = new Store();

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Vite
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_VITE_DEV_SERVER_URL: string;
declare const MAIN_WINDOW_VITE_NAME: string;

let mainWindow: BrowserWindow | null = null;

const createWindow = (): void => {
  // Create the browser window.
  mainWindow = new BrowserWindow({
    width: 1200,
    height: 800,
    minWidth: 1000,
    minHeight: 600,
    titleBarStyle: "hiddenInset",
    backgroundColor: "#ffffff",
    webPreferences: {
      preload: path.join(__dirname, "preload.js"),
      nodeIntegration: false,
      contextIsolation: true,
    },
  });

  // and load the index.html of the app.
  if (MAIN_WINDOW_VITE_DEV_SERVER_URL) {
    mainWindow.loadURL(MAIN_WINDOW_VITE_DEV_SERVER_URL);
  } else {
    mainWindow.loadFile(
      path.join(__dirname, `../renderer/${MAIN_WINDOW_VITE_NAME}/index.html`),
    );
  }

  // Open the DevTools in development.
  if (process.env.NODE_ENV === "development") {
    mainWindow.webContents.openDevTools();
  }
};

// Request audio permissions on macOS
const requestAudioPermissions = async () => {
  if (process.platform === "darwin") {
    const microphoneStatus =
      systemPreferences.getMediaAccessStatus("microphone");

    if (microphoneStatus !== "granted") {
      const granted = await systemPreferences.askForMediaAccess("microphone");
      if (!granted) {
        dialog.showMessageBox({
          type: "warning",
          title: "Microphone access required",
          message:
            "This app requires microphone access to record meetings.",
          buttons: ["OK"],
        });
      }
    }
  }
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on("ready", () => {
  createWindow();
  requestAudioPermissions();
});

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on("window-all-closed", () => {
  if (process.platform !== "darwin") {
    app.quit();
  }
});

app.on("activate", () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

// IPC handlers
ipcMain.handle("get-app-path", () => {
  return app.getPath("userData");
});

ipcMain.handle("store-get", (_, key: string) => {
  return (store as any).get(key, null);
});

ipcMain.handle("store-set", (_, key: string, value: any) => {
  (store as any).set(key, value);
  return true;
});

ipcMain.handle("store-delete", (_, key: string) => {
  (store as any).delete(key);
  return true;
});

// Audio source enumeration for system audio capture
ipcMain.handle("get-audio-sources", async () => {
  try {
    const sources = await desktopCapturer.getSources({
      types: ["window", "screen"],
    });

    return sources.map((source) => ({
      id: source.id,
      name: source.name,
      thumbnail: source.thumbnail.toDataURL(),
      display_id: source.display_id,
      appIcon: source.appIcon ? source.appIcon.toDataURL() : null,
    }));
  } catch (error) {
    console.error("Failed to get audio sources:", error);
    return [];
  }
});

// Request screen capture permissions on macOS
ipcMain.handle("request-screen-capture-permission", async () => {
  if (process.platform === "darwin") {
    try {
      const sources = await desktopCapturer.getSources({
        types: ["screen"],
      });
      return sources.length > 0;
    } catch (error) {
      console.error("Screen capture permission denied:", error);
      return false;
    }
  }
  return true; // Windows/Linux don't need explicit permission request
});

// Get available audio devices
ipcMain.handle("get-audio-devices", async () => {
  try {
    // This would be handled on the renderer side using navigator.mediaDevices.enumerateDevices()
    // We're just providing a bridge for future expansion
    return { success: true };
  } catch (error) {
    console.error("Failed to get audio devices:", error);
    return { success: false, error: (error as Error).message };
  }
});
